"""Build the detailed academic report from the implemented project facts."""
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import KeepTogether, PageBreak, Paragraph, Preformatted, SimpleDocTemplate, Spacer, Table, TableStyle

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "Vision_Inspector_Detailed_Project_Report.pdf"

styles = getSampleStyleSheet()
styles.add(ParagraphStyle(name="CoverTitle2", parent=styles["Title"], fontSize=28, leading=34, alignment=TA_CENTER, textColor=colors.HexColor("#0f172a"), spaceAfter=16))
styles.add(ParagraphStyle(name="CoverSub2", parent=styles["Normal"], fontSize=13, leading=18, alignment=TA_CENTER, textColor=colors.HexColor("#475569"), spaceAfter=22))
styles.add(ParagraphStyle(name="Section2", parent=styles["Heading1"], fontSize=18, leading=22, textColor=colors.HexColor("#0f766e"), spaceBefore=8, spaceAfter=8))
styles.add(ParagraphStyle(name="Sub2", parent=styles["Heading2"], fontSize=13, leading=16, textColor=colors.HexColor("#155e75"), spaceBefore=8, spaceAfter=5))
styles.add(ParagraphStyle(name="Body2", parent=styles["BodyText"], fontSize=9.4, leading=13, spaceAfter=5))
styles.add(ParagraphStyle(name="Small2", parent=styles["BodyText"], fontSize=8, leading=10))

def p(text, style="Body2"):
    return Paragraph(text, styles[style])

def bullets(items):
    return KeepTogether([p("- " + item) for item in items])

def table(rows, widths):
    t = Table(rows, colWidths=widths, repeatRows=1)
    t.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.45, colors.HexColor("#94a3b8")),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#ccfbf1")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8.2),
        ("LEADING", (0, 0), (-1, -1), 10),
        ("PADDING", (0, 0), (-1, -1), 5),
    ]))
    return t

def diagram(title, text):
    return [p(title, "Sub2"), Preformatted(text, styles["Small2"]), Spacer(1, 5)]

story = [Spacer(1, 0.9 * inch), p("Vision Inspector", "CoverTitle2"), p("Detailed Computer Vision Project Report", "CoverSub2"), p("VITyarthi - Build Your Own Project", "CoverSub2"), Spacer(1, 0.4 * inch), table([["Field", "Value"], ["Course", "Computer Vision"], ["Project type", "Classical image inspection dashboard"], ["Technology", "Python, OpenCV, NumPy, Streamlit, pytest"], ["Version", "1.0.0"], ["Student details", "To be completed before submission"]], [1.7 * inch, 4.8 * inch]), Spacer(1, 1.3 * inch), p("This report describes the implementation that exists in the repository. It does not claim model training, database persistence, performance benchmarks, or screenshots that were not produced.", "Small2"), PageBreak()]

story += [p("1. Introduction", "Section2"), p("Computer-vision datasets often require a quality check before annotation, training, or publication. Images may be dark, overexposed, blurry, low contrast, dominated by repetitive colors, or lacking useful visual structure. Manual inspection is slow and subjective. Vision Inspector is a local-first dashboard and command-line tool that creates an explainable first-pass inspection report for one PNG or JPEG image."), p("The project applies classical computer-vision concepts directly: grayscale statistics, color-space conversion, k-means clustering, Canny edge detection, contours, Otsu thresholding, and connected components. The design is intentionally lightweight so that a faculty evaluator can run and demonstrate it on a fresh machine."), p("2. Problem Statement", "Section2"), p("Given a local image, a user needs a repeatable way to identify common quality and structure issues before investing time in downstream computer-vision work. The system must provide understandable measurements and warnings without sending the image to a cloud service or making an opaque automated decision."), p("3. Motivation", "Section2"), bullets(["Reduce the time required for first-pass dataset triage.", "Connect syllabus concepts to a working real-world tool.", "Expose reasons behind a quality score instead of hiding them.", "Provide the same analysis engine through both an interactive UI and a CLI."]), p("4. Objectives", "Section2"), bullets(["Accept and validate a PNG/JPEG image.", "Calculate quality, color, and structure metrics.", "Return a typed, serializable inspection report.", "Provide useful success, warning, empty, and error states.", "Demonstrate the project with automated tests and a reproducible sample image."]), p("5. Target Users", "Section2"), bullets(["Computer-vision students learning image-processing fundamentals.", "Dataset curators performing an initial image audit.", "Developers debugging image-capture or preprocessing pipelines."]), p("6. Scope", "Section2"), p("In scope are single-image PNG/JPEG loading, validation, quality metrics, dominant-color analysis, structure metrics, dashboard presentation, JSON export, tests, diagrams, and an academic report. Out of scope are object identity recognition, face recognition, model training, cloud storage, persistent user accounts, batch processing, and automatic deletion or modification of source images."), PageBreak()]

story += [p("7. Functional Requirements", "Section2"), table([["ID", "Requirement", "Implementation evidence"], ["FR-1", "Accept one PNG/JPEG image.", "Streamlit uploader and CLI path argument"], ["FR-2", "Validate and decode input.", "pipeline.py checks path and cv2.imread result"], ["FR-3", "Analyze image quality.", "quality.py: brightness, contrast, blur, score, warnings"], ["FR-4", "Analyze color properties.", "colors.py: HSV colorfulness, mean RGB, k-means palette"], ["FR-5", "Analyze visual structure.", "structure.py: Canny, contours, Otsu, components"], ["FR-6", "Present and export results.", "Streamlit cards/tabs and CLI/download JSON"]], [0.55 * inch, 2.35 * inch, 3.6 * inch]), Spacer(1, 8), p("8. Non-Functional Requirements", "Section2"), table([["ID", "Requirement", "Design response"], ["NFR-1", "Performance", "Color clustering is bounded to an 80 x 80 thumbnail."], ["NFR-2", "Security and privacy", "Images are processed locally; no credentials or network API is required."], ["NFR-3", "Usability", "Plain-language labels, tabs, metrics, success, warning, and error states."], ["NFR-4", "Reliability", "Unreadable and missing files raise an actionable ValueError."], ["NFR-5", "Maintainability", "Single-purpose modules and typed dataclass result contracts."], ["NFR-6", "Resource efficiency", "No persistent database and bounded intermediate palette data."]], [0.65 * inch, 1.8 * inch, 4.05 * inch]), p("9. Assumptions and Constraints", "Section2"), bullets(["The input is a valid local image in a format supported by OpenCV.", "The quality score is heuristic and is not a production acceptance guarantee.", "The application analyzes one image per inspection.", "Thresholds are fixed in code for reproducible classroom demonstrations.", "No personal data or authentication is required for the prototype."]), PageBreak()]

story += [p("10. System Architecture", "Section2"), p("The system uses a small layered architecture. Presentation adapters are kept separate from domain algorithms. Both the Streamlit application and the CLI call the same pipeline, so the user interface does not duplicate computer-vision logic."), table([["Layer", "Responsibility", "Files"], ["Presentation", "Upload, display, download, and command-line formatting", "app.py, vision_inspector/cli.py"], ["Orchestration", "Validate input and coordinate modules", "vision_inspector/pipeline.py"], ["Domain algorithms", "Compute quality, color, and structure measurements", "quality.py, colors.py, structure.py"], ["Contracts", "Typed immutable outputs and JSON serialization", "models.py"], ["Verification", "Automated regression and edge-case tests", "tests/test_pipeline.py"]], [1.25 * inch, 3.0 * inch, 2.25 * inch]), Spacer(1, 8), *diagram("Architecture diagram", "User\n  |\n  +--> Streamlit dashboard ----+\n  |                            |\n  +--> CLI --------------------+--> Analysis pipeline\n                                      |\n                         +------------+------------+\n                         |            |            |\n                    Quality        Color       Structure\n                         +------------+------------+\n                                      |\n                            InspectionReport\n                              /          \\\n                       Dashboard       JSON export"), p("11. Major Modules", "Section2"), table([["Module", "Purpose", "Key CV concepts"], ["Quality analysis", "Find exposure, contrast, and blur signals.", "Grayscale mean/std, Laplacian variance"], ["Color analysis", "Summarize colorfulness and dominant colors.", "BGR to RGB/HSV, saturation, k-means"], ["Structure analysis", "Describe edges and foreground-like regions.", "Canny, contours, Otsu, connected components"], ["Pipeline/reporting", "Provide one stable output contract.", "Validation, dataclasses, JSON serialization"]], [1.45 * inch, 3.1 * inch, 1.95 * inch]), PageBreak()]

story += [p("12. Detailed Algorithm Design", "Section2"), p("12.1 Quality analysis", "Sub2"), p("The BGR image is converted to grayscale. Brightness is the grayscale mean, contrast is the grayscale standard deviation, and blur score is the variance of the Laplacian. Warnings are generated for underexposure, overexposure, low contrast, and possible blur. The heuristic score combines exposure, contrast, and sharpness components into a bounded 0-100 value."), p("12.2 Color analysis", "Sub2"), p("The image is resized to 80 x 80 before clustering to bound cost. OpenCV k-means groups pixels into five color centers using fixed criteria. Centers are converted from BGR to RGB and ordered by pixel frequency. Colorfulness is estimated from average HSV saturation, and mean RGB is calculated from the full image."), p("12.3 Structure analysis", "Sub2"), p("The grayscale image is processed with Canny edge detection. Edge density is the percentage of nonzero edge pixels. External contours are extracted from the edge map and the largest contour area is normalized by total image area. Otsu thresholding creates a binary image for connected-component counting."), p("13. Input/Output Contract", "Section2"), p("Input: a filesystem path or uploaded PNG/JPEG. Output: `InspectionReport(filename, width, height, channels, quality, colors, structure)`. Quality, color, and structure are immutable dataclasses. `to_dict()` supports programmatic use and `to_json()` supports the CLI, download button, and integrations."), p("14. Storage and Schema Design", "Section2"), p("The system intentionally uses no persistent database. The source image is not copied permanently and the Streamlit upload is written only to a temporary local file for analysis. The report is held in memory and can be serialized as JSON. The ER diagram in `docs/diagrams/er-diagram.mmd` represents the report object composition rather than database tables."), p("15. Security Considerations", "Section2"), bullets(["No hard-coded secrets, passwords, or API keys.", "No external upload or remote inference service.", "Temporary upload path is used only for the current inspection.", "Source images are not modified or deleted.", "The tool provides advisory metrics, not high-stakes automated decisions."]), PageBreak()]

story += [p("16. User Workflow", "Section2"), p("A user selects a PNG/JPEG image, the application validates and decodes it, then runs the three analysis modules. The dashboard displays a summary and module tabs. The user can review warnings, inspect detailed metrics, and download JSON. The CLI follows the same pipeline and prints either a concise summary or formatted JSON."), *diagram("Workflow diagram", "START\n  |\nSelect image\n  |\nReadable? -- no --> Actionable error --> END\n  | yes\nRun quality + color + structure modules\n  |\nAssemble typed report\n  |\nReview dashboard or export JSON\n  |\nEND"), p("17. UML Design Artifacts", "Section2"), *diagram("Use case diagram", "Dataset curator --> (Upload image)\nDataset curator --> (Review warnings)\nDataset curator --> (Explore colors and structure)\nDeveloper -------> (Run CLI analysis)\nDeveloper -------> (Export JSON)\nAll use cases ------> Vision Inspector"), *diagram("Component/class diagram", "App ----> Pipeline ----> Quality\n  |          |----------> Colors\n  |          |----------> Structure\nCLI --------+----------> InspectionReport\n                         |--> to_dict()\n                         +--> to_json()"), *diagram("Sequence diagram", "User -> UI/CLI: provide image\nUI/CLI -> Pipeline: analyze_image(path)\nPipeline -> Validator: check and decode\nPipeline -> CV modules: run three analyses\nCV modules --> Pipeline: typed results\nPipeline -> Report: assemble\nReport --> UI/CLI: display or serialize"), p("The authoritative Mermaid sources are stored in `docs/diagrams/` and correspond to the implemented modules."), PageBreak()]

story += [p("18. Implementation Details", "Section2"), p("The repository contains a reusable Python package, a Streamlit entry point, a CLI entry point, a deterministic demo-image generator, automated tests, Markdown documentation, Mermaid diagrams, and report builders. The UI uses temporary files for uploads and handles invalid input with a visible error. The CLI shares the same pipeline and therefore has identical measurements."), p("19. Testing Approach", "Section2"), table([["Test", "Purpose", "Observed result"], ["Synthetic valid PNG", "Validate dimensions and metric bounds.", "Passed"], ["Unreadable text file", "Validate actionable input error.", "Passed"], ["JSON contract", "Ensure all modules serialize predictably.", "Passed"], ["Missing path", "Validate missing-file handling.", "Passed"], ["Live Streamlit upload", "Verify dashboard workflow and module tabs.", "Verified"]], [1.7 * inch, 3.1 * inch, 1.65 * inch]), p("Automated verification completed with 4 passed tests. No fabricated performance benchmark or accuracy claim is included because the project is a heuristic inspection tool rather than a trained predictive model."), p("20. Runtime Results", "Section2"), p("The reproducible demo image `data/sample_scene.png` produced the following actual CLI report: image size 720 x 480 with 3 channels; quality score 73.83/100; brightness 158.08; contrast 45.81; blur score 435.22; colorfulness 48.95%; mean RGB (163, 162, 117); edge density 1.36%; largest contour ratio 0.6774; connected components 2; no quality warnings."), p("The live dashboard displayed the uploaded image, summary cards, a no-warning success state, the quality tab, the color tab with palette, the structure tab, and the JSON download control."), PageBreak()]

story += [p("21. Design Decisions and Rationale", "Section2"), bullets(["Classical CV: transparent and directly aligned with introductory CV concepts.", "Single-image workflow: small enough to demonstrate reliably and easy to understand.", "Typed dataclasses: stable contracts for UI, CLI, tests, and JSON.", "No database: persistence is not needed for a one-image advisory analysis.", "Bounded k-means input: keeps the demonstration responsive and resource efficient.", "Human-readable warnings: preserve interpretability alongside the score."]), p("22. Challenges Faced", "Section2"), bullets(["A single score can hide causes, so component metrics remain visible.", "Color clustering can be expensive, so a bounded thumbnail is used.", "The same behavior must be consistent between a browser UI and CLI, so both call one pipeline."]), p("23. Learnings and Key Takeaways", "Section2"), bullets(["Classical CV primitives can support practical dataset triage without model training.", "Separating algorithms from presentation improves testability and reuse.", "A measurement plus an explanation is more useful than an unexplained score.", "Reproducible sample data helps faculty demonstrate the project quickly."]), p("24. Future Enhancements", "Section2"), bullets(["Batch directory analysis with CSV/JSONL export.", "Configurable thresholds and saved inspection profiles.", "Perceptual-hash duplicate detection.", "Interactive plots and before/after enhancement previews.", "Optional ML detector as a separate, clearly labeled module."]), p("25. References", "Section2"), bullets(["VITyarthi, Build Your Own Project: General Project Instructions and Submission Guidelines, provided assignment PDF.", "OpenCV documentation for image processing, color conversion, k-means, Canny, contours, thresholding, and connected components.", "NumPy documentation for array statistics and reshaping.", "Streamlit documentation for file upload, tabs, metrics, and download buttons."]), p("26. Submission Checklist", "Section2"), table([["Deliverable", "Location"], ["Source code", "app.py, vision_inspector/, scripts/"], ["Automated tests", "tests/test_pipeline.py"], ["README and statement", "README.md, statement.md"], ["Design documentation", "docs/*.md"], ["Diagrams", "docs/diagrams/*.mmd"], ["Report", "This PDF and Vision_Inspector_Project_Report.pdf"], ["Demo image", "data/sample_scene.png"]], [2.2 * inch, 4.25 * inch]), Spacer(1, 10), p("Manual fields before portal submission: student name, registration/roll number, faculty name, semester, academic year, and any faculty-specific cover-page format. Runtime screenshots should be saved in docs/screenshots if the submission portal requires image files.", "Small2")]

def footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#64748b"))
    canvas.drawString(0.7 * inch, 0.45 * inch, "Vision Inspector | Detailed VITyarthi Report")
    canvas.drawRightString(7.8 * inch, 0.45 * inch, f"Page {doc.page}")
    canvas.restoreState()

OUT.parent.mkdir(exist_ok=True)
SimpleDocTemplate(str(OUT), pagesize=letter, rightMargin=0.7 * inch, leftMargin=0.7 * inch, topMargin=0.65 * inch, bottomMargin=0.65 * inch, title="Vision Inspector Detailed Project Report").build(story, onFirstPage=footer, onLaterPages=footer)
print(OUT)
